In [ ]:
import numpy as np
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
inputs.shape
(4, 2)
outputs = np.array([0, 0, 0, 1])
outputs.shape
(4,)
weights = np.array([0.5, 0.5])
learning_rate = 0.1

In [ ]:
def step_function(sum):
 if (sum >= 1):
  return 1
 return 0


In [ ]:
def calculate_output(instance):
 s = instance.dot(weights)
 return step_function(s)
calculate_output(np.array([[1,1]]))

1

In [ ]:
len(outputs)

4

In [ ]:
inputs[3]

array([1, 1])

In [ ]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [ ]:
inputs[1]

array([0, 1])

In [ ]:
inputs[1][0]

0

In [ ]:
inputs[1][1]

1

In [ ]:
def train():
 total_error = 1
 while (total_error != 0):
  total_error = 0
 for i in range(len(outputs)):
  prediction = calculate_output(inputs[i])
  error = abs(outputs[i] - prediction)
  total_error += error
 if error > 0:
  for j in range(len(weights)):
    weights[j] = weights[j] + (learning_rate * inputs[i][j] *error)
    print('Weight updated: ' + str(weights[j]))
 print('Total error: ' + str(total_error))
train()

Total error: 0


In [ ]:
weights

array([0.5, 0.5])

In [ ]:
calculate_output(np.array([0,0]))

0

In [ ]:
calculate_output(np.array([0,1]))

0

In [ ]:
calculate_output(np.array([1,0]))

0

In [ ]:
calculate_output(np.array([1,1]))

1